services:
  db:
    image: postgres:16-alpine
    container_name: tgchats_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-telegram_chats}
    ports:
      - "${DB_PORT:-15432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-telegram_chats}"]
      interval: 5s
      timeout: 3s
      retries: 10

  saver:
    build:
      context:
        ./saver
      dockerfile:
        ./Dockerfile
    container_name: saver_app
    depends_on:
      db:
        condition: service_healthy
    env_file: saver/.env
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT:-5432}
    volumes:
      - ./saver/migrations:/saver_app/migrations
      - ./saver/migrations.ini:/saver_app/migrations.ini:ro
    ports:
      - "8000:8000"
    #command: ["uvicorn","saver_app.main:saver_app","--host","0.0.0.0","--port","8000","--reload"]
    #command: uvicorn src.saver_app.main:app --host 0.0.0.0 --port 8000 --reload

  tgbot:
    build:
      context:
        ./bot
      dockerfile:
        ./Dockerfile
    container_name: bot_app
    env_file: "tg.env"
    ports:
      - "6677"

  summarizer:
    build: summarizer
    env_file: .env
    ports:
      - "1234:8080"

volumes:
  pgdata: {}
