services:
  db:
    image: postgres:16-alpine
    container_name: tgchats_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-telegram_chats}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-telegram_chats}"]
      interval: 5s
      timeout: 3s
      retries: 10

  saver:
    build: saver
    container_name: tgchats_app
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      PYTHONPATH: /app
      DB_HOST: db
      DB_PORT: ${DB_PORT:-5432}
    volumes:
      - ./saver/alembic:/app/alembic
      - ./saver/alembic.ini:/app/alembic.ini:ro
    ports:
      - "8000:8000"
    command: ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000","--reload"]

  tgbot:
    build: bot
    env_file: "tg.env"
volumes:
  pgdata: {}
