"""added chat_title to message table

Revision ID: d0ab5a195edd
Revises: e446cf95ba08
Create Date: 2025-12-07 04:08:45.946644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ab5a195edd'
down_revision: Union[str, Sequence[str], None] = 'e446cf95ba08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('chat_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'chat_title')
    # ### end Alembic commands ###
