"""Add groups

Revision ID: e446cf95ba08
Revises: 51302249d6a2
Create Date: 2025-12-05 14:58:56.998993

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e446cf95ba08'
down_revision: Union[str, Sequence[str], None] = '51302249d6a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('group',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('group_pkey'))
                    )
    op.create_table('groupmembership',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('groupmembership_pkey'))
                    )
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_chat_time'), table_name='messages')
    op.drop_index(op.f('ix_messages_content_trgm'), table_name='messages', postgresql_ops={'content': 'gin_trgm_ops'},
                  postgresql_using='gin')
    op.drop_index(op.f('ix_messages_forward_from_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_reply_to_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_time_sent'), table_name='messages')
    op.drop_index(op.f('ix_messages_tsv'), table_name='messages', postgresql_using='gin')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groupmembership')
    op.drop_table('group')

    op.create_table('messages',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
                    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
                    sa.Column('message_id', sa.BIGINT(), autoincrement=False, nullable=False),
                    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('is_service', sa.BOOLEAN(), autoincrement=False, nullable=False),
                    sa.Column('reply_to_message_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('forward_from_user_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('time_sent', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
                    sa.Column('time_loaded', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              autoincrement=False, nullable=False),
                    sa.Column('tsv', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
                    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey')),
                    sa.UniqueConstraint('chat_id', 'message_id', name=op.f('uq_chat_msg'), postgresql_include=[],
                                        postgresql_nulls_not_distinct=False)
                    )
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_messages_tsv'), 'messages', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_messages_time_sent'), 'messages', ['time_sent'], unique=False)
    op.create_index(op.f('ix_messages_reply_to_message_id'), 'messages', ['reply_to_message_id'], unique=False)
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_messages_forward_from_user_id'), 'messages', ['forward_from_user_id'], unique=False)
    op.create_index(op.f('ix_messages_content_trgm'), 'messages', ['content'], unique=False,
                    postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_messages_chat_time'), 'messages', ['chat_id', 'time_sent'], unique=False)
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    # ### end Alembic commands ###
