[project]
name = "bot_app"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "aiogram (==3.22.0)"
]


[[tool.poetry.packages]]
include = "bot_app"
from = "src"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
