"""create table messages without encryption

Revision ID: cc06ea481a93
Revises: 
Create Date: 2025-10-03 15:56:00.243599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc06ea481a93'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_service', sa.Boolean(), nullable=False),
    sa.Column('reply_to_message_id', sa.BigInteger(), nullable=True),
    sa.Column('forward_from_user_id', sa.BigInteger(), nullable=True),
    sa.Column('time_sent', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_loaded', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'message_id', name='uq_chat_msg')
    )
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_index('ix_messages_chat_time', 'messages', ['chat_id', 'time_sent'], unique=False)
    op.create_index('ix_messages_content_trgm', 'messages', ['content'], unique=False, postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.create_index(op.f('ix_messages_forward_from_user_id'), 'messages', ['forward_from_user_id'], unique=False)
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_messages_reply_to_message_id'), 'messages', ['reply_to_message_id'], unique=False)
    op.create_index(op.f('ix_messages_time_sent'), 'messages', ['time_sent'], unique=False)
    op.create_index('ix_messages_tsv', 'messages', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index('ix_messages_tsv', table_name='messages', postgresql_using='gin')
    op.drop_index(op.f('ix_messages_time_sent'), table_name='messages')
    op.drop_index(op.f('ix_messages_reply_to_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_forward_from_user_id'), table_name='messages')
    op.drop_index('ix_messages_content_trgm', table_name='messages', postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.drop_index('ix_messages_chat_time', table_name='messages')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
